name: Streamlit App CI/CD
run-name: Running CI/CD for our web application 🚀

on:
    push:
        tags:
            - "st_solution-v*"

jobs:

    # Job for building and pushing the Docker image to ACR
    build-and-push-docker-image:
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Log in to Azure Container Registry
            uses: azure/docker-login@v2
            with:
                login-server: ${{ secrets.DOCKER_REGISTRY }}
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Build Docker image
            run: |
              docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.ref_name }} ./websolution_st
              docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.ref_name }} ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

          - name: Push Docker image to ACR
            run: |
              docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}
              docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:latest

    # Job to deploy the Docker image to the containerized Azure Web App
    deploy-to-azure:
        name: Deploy to Azure Web App
        runs-on: ubuntu-latest
        needs: build-and-push-docker-image
        steps:
          - name: Login to Azure
            uses: azure/login@v1
            with:
              creds: ${{ secrets.AZURE_CREDENTIALS }}

          - name: Deploy Docker container to Azure Web App
            uses: azure/webapps-deploy@v2
            with:
              app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
              images: ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.IMAGE_NAME }}:${{ github.ref_name }}
